server:
  port: 8081

spring:
  application:
    name: api-concert-tickets
  datasource:
    url: jdbc:mariadb://localhost:3307/db_concert_tickets
    username: tickets_user
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    show-sql: true

springdoc:
  api-docs:
    enabled: true
    path: /api/docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html